config/routes.rb
Rails.application.routes.draw do
  get 'register' => 'users#new'
  post 'register' => 'users#create'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'

  resources :games, only: [:new, :create, :show] do
  end
  resources :boards, only: [] do
    post '/move/:position' => 'board_moves#create', as: :move
  end

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  X_AXIS = ("A".."L").to_a.freeze
  Y_AXIS = (1..12).to_a.freeze

  belongs_to :game
  belongs_to :user, optional: true
  has_many :pieces
  has_many :piece_positions
  has_many :board_moves

  after_save :trigger_hits!

  def trigger_hits!
    raise self.inspect
  end

  def randomize_pieces!
    sizes = Piece::SIZES
    sizes.each do |psize|
      piece = self.pieces.build
      piece.randomize_position(psize)
      piece.randomize_position(psize) while piece.position_conflict?
      piece.save!
    end
  end
end

app/models/board_move.rb
class BoardMove < ApplicationRecord
  belongs_to :board
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :boards
end

app/models/piece.rb
class Piece < ApplicationRecord
  belongs_to :board
  has_many :piece_positions

  SIZES = (2..5).to_a.freeze

  def position_conflict?
    other_positions = self.board.piece_positions.reload
    positions = self.piece_positions
    positions.any? { |pos| other_positions.map(&:position).include?(pos.position) }
  end

  def randomize_position(psize)
    dir = [:x, :y].sample

    x_axis = Board::X_AXIS
    y_axis = Board::Y_AXIS

    x1 = x_axis.sample
    y1 = y_axis.sample

    x2 = dir == :x ? get_valid_endpoint(x1, x_axis, psize) : x1
    y2 = dir == :y ? get_valid_endpoint(y1, y_axis, psize) : y1

    coords = dir == :y ? [y1, y2].sort : [x1, x2].sort

    positions = (coords[0]..coords[1]).to_a.map { |v| dir == :y ? "#{x1}#{v}" : "#{v}#{y1}" }

    self.piece_positions = positions.map { |pos| PiecePosition.new(piece: self, position: pos, board: board) }
    self.psize = psize

    true
  end

  def get_valid_endpoint(start, axis, psize)
    amnt = psize - 1
    idx = axis.index(start)

    val = [idx, amnt].inject([:+, :-].sample)
    val = [idx, amnt].inject(:+) if val < 0
    val = [idx, amnt].inject(:-) if val > (axis.size - 1)

    axis[val]
  end

  def color
    case psize
    when 2 then 'blue'
    when 3 then 'purple'
    when 4 then 'green'
    when 5 then 'yellow'
    end
  end
end

app/models/piece_position.rb
class PiecePosition < ApplicationRecord
  belongs_to :board
  belongs_to :piece
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_token :uuid
  has_secure_password
  validates :email, presence: true, uniqueness: {case_sensitive: false}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_user

  def self.current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by(uuid: session[:uuid]) if session[:uuid].present?
  end
  helper_method :current_user

  private

    def require_user
      redirect_to(login_path) unless current_user
    end
end

app/controllers/board_moves_controller.rb
class BoardMovesController < ApplicationController
  def create
    board = Board.find(params[:board_id])
    move = board.board_moves.create!(position: params[:position])

    redirect_to game_path(board.game)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def new
  end

  def create
    @game = Game.create!
    @boards = 2.times.map { |x| @game.boards.create! }
    @boards.map(&:randomize_pieces!)

    redirect_to game_path(@game)
  end

  def show
    @game = Game.find(params[:id])

    # @game.boards.map { |b| b.pieces.destroy_all }
    # @game.boards.map(&:randomize_pieces!)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_user, only: [:new, :create]

  def new
  end

  def create
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_user, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(params.require(:user).permit(:email, :password, :password_confirmation))

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path, notice: "sdkfjdlkfjsd" }
      else
        format.html { render :new }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/games/new.html.erb
<%= button_to "Create Game", games_path %>

app/views/games/show.html.erb
<% @game.boards.each do |board| %>
  <% positions = board.piece_positions.includes(:piece) %>

  <div class="board" style="width: 100%; max-width: 480px;">
    <% Board::X_AXIS.each do |x| %>
      <div class="row" style="width: 100%;">
        <% Board::Y_AXIS.each do |y| %>
          <%
            coords ="#{x}#{y}"
            checked = positions.detect { |pos| pos.position == coords } || board.board_moves.any? { |m| m.position == coords } %>
          <div class="cell<%= ' checked' if checked %>" style="width: <%= 100.0 / Board::Y_AXIS.size %>%; border: 1px solid; box-sizing: border-box; float: left;<%= " background: #{checked.piece.color};" if checked.is_a?(PiecePosition) %><%= " background: #888;" if checked == true %>;">
            <%= link_to_unless checked, "&nbsp;".html_safe, board_move_path(board, coords), class: "cell-link", method: :post %>
          </div>
        <% end %>
        <div style="clear: both;"></div>
      </div>
    <% end %>
  </div><br>
<% end %>

<style type="text/css">
  .cell-link {
    display: inline-block;
    height: 100%;
    width: 100%;
    text-decoration: none;
  }
  .cell.checked {
  }
  .cell:not(.checked) .cell-link:hover {
    background: #eee;
  }

</style>

<script type="text/javascript">
  var cells = document.querySelectorAll(".cell")

  for (i = 0; i < cells.length; i++) {
    cells[i].style.height = cells[i].offsetWidth + "px";
  }
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Battleship</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<%= form_for @user, url: register_path do |f| %>
  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>

  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>